language: ruby
script:
  - chmod 600 travis
  - ssh-agent -s
  - ssh-add travis
  - bundle
  - bundle exec rake deploy

before_install:
- openssl aes-256-cbc -K $encrypted_3d9d8b8ca0bb_key -iv $encrypted_3d9d8b8ca0bb_iv
  -in travis.enc -out travis -d
