language: ruby
script:
  - chmod 600 travis
  - ssh-add travis
  - git remote rm origin
  - git remote add origin git@github.com:releu/releu.github.io.git
  - git config --global user.email "releu+travis@me.com"
  - git config --global user.name "Releu Travis"
  - bundle
  - bundle exec rake deploy

before_install:
- openssl aes-256-cbc -K $encrypted_3d9d8b8ca0bb_key -iv $encrypted_3d9d8b8ca0bb_iv
  -in travis.enc -out travis -d

branches:
  only:
    - engine
